<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2656" started-at="2019-12-03T02:08:07Z" finished-at="2019-12-03T02:08:09Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2656" started-at="2019-12-03T02:08:07Z" finished-at="2019-12-03T02:08:09Z">
      <class name="ci.workshop.test.testDelegate.TestServicioDelegate">
        <test-method status="PASS" signature="initMocks()[pri:0, instance:ci.workshop.test.testDelegate.TestServicioDelegate@1e127982]" name="initMocks" is-config="true" duration-ms="2522" started-at="2019-12-02T21:08:07Z" finished-at="2019-12-02T21:08:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initMocks -->
        <test-method status="FAIL" signature="testDelete()[pri:0, instance:ci.workshop.test.testDelegate.TestServicioDelegate@1e127982]" name="testDelete" duration-ms="57" started-at="2019-12-02T21:08:09Z" finished-at="2019-12-02T21:08:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected null, but was:<ci.workshop.test.model.Tmio1Servicio@61884cb1>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected null, but was:<ci.workshop.test.model.Tmio1Servicio@61884cb1>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotNull(Assert.java:755)
	at org.junit.Assert.assertNull(Assert.java:737)
	at org.junit.Assert.assertNull(Assert.java:747)
	at ci.workshop.test.testDelegate.TestServicioDelegate.testDelete(TestServicioDelegate.java:257)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDelete -->
        <test-method status="PASS" signature="testFindByHash()[pri:0, instance:ci.workshop.test.testDelegate.TestServicioDelegate@1e127982]" name="testFindByHash" duration-ms="16" started-at="2019-12-02T21:08:09Z" finished-at="2019-12-02T21:08:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFindByHash -->
        <test-method status="PASS" signature="testServiceFindAll()[pri:0, instance:ci.workshop.test.testDelegate.TestServicioDelegate@1e127982]" name="testServiceFindAll" duration-ms="16" started-at="2019-12-02T21:08:09Z" finished-at="2019-12-02T21:08:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testServiceFindAll -->
        <test-method status="PASS" signature="testSaveService()[pri:0, instance:ci.workshop.test.testDelegate.TestServicioDelegate@1e127982]" name="testSaveService" duration-ms="0" started-at="2019-12-02T21:08:09Z" finished-at="2019-12-02T21:08:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSaveService -->
      </class> <!-- ci.workshop.test.testDelegate.TestServicioDelegate -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
